/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20Supplies,
  IERC20SuppliesInterface,
} from "../../interfaces/IERC20Supplies";

const _abi = [
  {
    inputs: [],
    name: "maxSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC20Supplies__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20SuppliesInterface {
    return new utils.Interface(_abi) as IERC20SuppliesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Supplies {
    return new Contract(address, _abi, signerOrProvider) as IERC20Supplies;
  }
}
