/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20Transfer,
  IERC20TransferInterface,
} from "../../interfaces/IERC20Transfer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
];

export class IERC20Transfer__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20TransferInterface {
    return new utils.Interface(_abi) as IERC20TransferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Transfer {
    return new Contract(address, _abi, signerOrProvider) as IERC20Transfer;
  }
}
